
-- Add many more global news outlets to approved_domains
INSERT INTO approved_domains (name, domain, feed_url, country_code, region, language, source_type, priority) VALUES
-- WIRE SERVICES
('Reuters', 'reuters.com', 'https://www.reutersagency.com/feed/', 'GB', 'wire', 'en', 'rss', 95),
('AFP', 'afp.com', NULL, 'FR', 'wire', 'fr', 'html', 80),
('UPI', 'upi.com', 'https://rss.upi.com/news/news.rss', 'US', 'wire', 'en', 'rss', 80),
('Xinhua', 'english.news.cn', 'http://www.xinhuanet.com/english/rss/worldrss.xml', 'CN', 'wire', 'en', 'rss', 75),
('TASS', 'tass.com', 'https://tass.com/rss/v2.xml', 'RU', 'wire', 'en', 'rss', 70),
('Kyodo News', 'english.kyodonews.net', NULL, 'JP', 'wire', 'en', 'html', 70),
('EFE', 'efe.com', NULL, 'ES', 'wire', 'es', 'html', 70),
('ANSA', 'ansa.it', 'https://www.ansa.it/sito/ansait_rss.xml', 'IT', 'wire', 'it', 'rss', 70),
('PA Media', 'pamediagroup.com', NULL, 'GB', 'wire', 'en', 'html', 65),
('PTI', 'ptinews.com', NULL, 'IN', 'wire', 'en', 'html', 65),

-- US PRESS
('USA Today', 'usatoday.com', 'http://rssfeeds.usatoday.com/usatoday-NewsTopStories', 'US', 'press', 'en', 'rss', 85),
('Los Angeles Times', 'latimes.com', 'https://www.latimes.com/world-nation/rss2.0.xml', 'US', 'press', 'en', 'rss', 85),
('Wall Street Journal', 'wsj.com', 'https://feeds.a.dj.com/rss/RSSWorldNews.xml', 'US', 'press', 'en', 'rss', 90),
('Chicago Tribune', 'chicagotribune.com', 'https://www.chicagotribune.com/arcio/rss/', 'US', 'press', 'en', 'rss', 75),
('NPR', 'npr.org', 'https://feeds.npr.org/1001/rss.xml', 'US', 'press', 'en', 'rss', 85),
('PBS NewsHour', 'pbs.org', 'https://www.pbs.org/newshour/feeds/rss/headlines', 'US', 'press', 'en', 'rss', 80),
('Politico', 'politico.com', 'https://rss.politico.com/politics-news.xml', 'US', 'press', 'en', 'rss', 80),
('The Hill', 'thehill.com', 'https://thehill.com/feed/', 'US', 'press', 'en', 'rss', 75),
('Bloomberg', 'bloomberg.com', NULL, 'US', 'business', 'en', 'html', 90),
('Forbes', 'forbes.com', 'https://www.forbes.com/real-time/feed2/', 'US', 'business', 'en', 'rss', 80),
('Business Insider', 'businessinsider.com', 'https://feeds.businessinsider.com/custom/all', 'US', 'business', 'en', 'rss', 80),
('CNBC', 'cnbc.com', 'https://www.cnbc.com/id/100003114/device/rss/rss.html', 'US', 'business', 'en', 'rss', 85),

-- UK PRESS
('The Times', 'thetimes.com', NULL, 'GB', 'press', 'en', 'html', 85),
('Daily Telegraph', 'telegraph.co.uk', 'https://www.telegraph.co.uk/rss.xml', 'GB', 'press', 'en', 'rss', 85),
('Daily Mail', 'dailymail.co.uk', 'https://www.dailymail.co.uk/articles.rss', 'GB', 'press', 'en', 'rss', 75),
('The Economist', 'economist.com', NULL, 'GB', 'press', 'en', 'html', 90),
('Evening Standard', 'standard.co.uk', 'https://www.standard.co.uk/rss', 'GB', 'press', 'en', 'rss', 70),
('The Mirror', 'mirror.co.uk', 'https://www.mirror.co.uk/news/rss.xml', 'GB', 'press', 'en', 'rss', 65),
('ITV News', 'itv.com', 'https://www.itv.com/news/rss', 'GB', 'press', 'en', 'rss', 75),
('Channel 4 News', 'channel4.com', NULL, 'GB', 'press', 'en', 'html', 70),

-- EUROPE
('Der Spiegel', 'spiegel.de', 'https://www.spiegel.de/international/index.rss', 'DE', 'europe', 'en', 'rss', 85),
('Die Zeit', 'zeit.de', 'https://newsfeed.zeit.de/index', 'DE', 'europe', 'de', 'rss', 80),
('Süddeutsche Zeitung', 'sueddeutsche.de', 'https://rss.sueddeutsche.de/rss/Topthemen', 'DE', 'europe', 'de', 'rss', 80),
('FAZ', 'faz.net', 'https://www.faz.net/rss/aktuell/', 'DE', 'europe', 'de', 'rss', 80),
('Handelsblatt', 'handelsblatt.com', 'https://www.handelsblatt.com/contentexport/feed/top', 'DE', 'europe', 'de', 'rss', 75),
('Le Monde', 'lemonde.fr', 'https://www.lemonde.fr/rss/une.xml', 'FR', 'europe', 'fr', 'rss', 90),
('Le Figaro', 'lefigaro.fr', 'https://www.lefigaro.fr/rss/figaro_actualites.xml', 'FR', 'europe', 'fr', 'rss', 80),
('Libération', 'liberation.fr', 'https://www.liberation.fr/arc/outboundfeeds/rss/', 'FR', 'europe', 'fr', 'rss', 75),
('Les Echos', 'lesechos.fr', 'https://syndication.lesechos.fr/rss/rss_une.xml', 'FR', 'europe', 'fr', 'rss', 75),
('El País', 'elpais.com', 'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada', 'ES', 'europe', 'es', 'rss', 85),
('El Mundo', 'elmundo.es', 'https://e00-elmundo.uecdn.es/elmundo/rss/portada.xml', 'ES', 'europe', 'es', 'rss', 80),
('La Repubblica', 'repubblica.it', 'https://www.repubblica.it/rss/homepage/rss2.0.xml', 'IT', 'europe', 'it', 'rss', 85),
('Corriere della Sera', 'corriere.it', 'https://xml2.corriereobjects.it/rss/homepage.xml', 'IT', 'europe', 'it', 'rss', 80),
('NRC', 'nrc.nl', 'https://www.nrc.nl/rss/', 'NL', 'europe', 'nl', 'rss', 75),
('De Volkskrant', 'volkskrant.nl', NULL, 'NL', 'europe', 'nl', 'html', 70),
('NOS', 'nos.nl', 'https://feeds.nos.nl/nosnieuwsalgemeen', 'NL', 'europe', 'nl', 'rss', 80),
('RTE', 'rte.ie', 'https://www.rte.ie/feeds/rss/?index=/news/', 'IE', 'europe', 'en', 'rss', 75),
('The Irish Times', 'irishtimes.com', 'https://www.irishtimes.com/cmlink/the-irish-times-news-1.1319192', 'IE', 'europe', 'en', 'rss', 75),
('Politiken', 'politiken.dk', NULL, 'DK', 'nordics', 'da', 'html', 70),
('Berlingske', 'berlingske.dk', NULL, 'DK', 'nordics', 'da', 'html', 70),
('VG', 'vg.no', 'https://www.vg.no/rss/feed', 'NO', 'nordics', 'no', 'rss', 75),
('Aftenposten', 'aftenposten.no', NULL, 'NO', 'nordics', 'no', 'html', 75),
('NRK', 'nrk.no', 'https://www.nrk.no/toppsaker.rss', 'NO', 'nordics', 'no', 'rss', 80),
('Helsingin Sanomat', 'hs.fi', NULL, 'FI', 'nordics', 'fi', 'html', 70),
('YLE', 'yle.fi', 'https://feeds.yle.fi/uutiset/v1/recent.rss?publisherIds=YLE_UUTISET', 'FI', 'nordics', 'fi', 'rss', 80),
('SRF', 'srf.ch', NULL, 'CH', 'europe', 'de', 'html', 70),
('Tages-Anzeiger', 'tagesanzeiger.ch', NULL, 'CH', 'europe', 'de', 'html', 70),
('RTP', 'rtp.pt', NULL, 'PT', 'europe', 'pt', 'html', 65),
('Público', 'publico.pt', NULL, 'PT', 'europe', 'pt', 'html', 65),
('Kathimerini', 'ekathimerini.com', NULL, 'GR', 'europe', 'en', 'html', 65),
('Euronews', 'euronews.com', 'https://www.euronews.com/rss', 'FR', 'europe', 'en', 'rss', 80),
('Politico EU', 'politico.eu', 'https://www.politico.eu/feed/', 'BE', 'europe', 'en', 'rss', 80),

-- ASIA-PACIFIC
('South China Morning Post', 'scmp.com', 'https://www.scmp.com/rss/91/feed', 'HK', 'asia', 'en', 'rss', 85),
('The Straits Times', 'straitstimes.com', NULL, 'SG', 'asia', 'en', 'html', 80),
('Channel News Asia', 'channelnewsasia.com', 'https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml', 'SG', 'asia', 'en', 'rss', 80),
('Japan Times', 'japantimes.co.jp', 'https://www.japantimes.co.jp/feed/', 'JP', 'asia', 'en', 'rss', 80),
('NHK World', 'www3.nhk.or.jp', 'https://www3.nhk.or.jp/rss/news/cat0.xml', 'JP', 'asia', 'en', 'rss', 80),
('Times of India', 'timesofindia.indiatimes.com', 'https://timesofindia.indiatimes.com/rssfeedstopstories.cms', 'IN', 'asia', 'en', 'rss', 85),
('The Hindu', 'thehindu.com', 'https://www.thehindu.com/feeder/default.rss', 'IN', 'asia', 'en', 'rss', 80),
('NDTV', 'ndtv.com', 'https://feeds.feedburner.com/ndtvnews-top-stories', 'IN', 'asia', 'en', 'rss', 80),
('Korea Herald', 'koreaherald.com', NULL, 'KR', 'asia', 'en', 'html', 75),
('Taipei Times', 'taipeitimes.com', NULL, 'TW', 'asia', 'en', 'html', 70),
('Bangkok Post', 'bangkokpost.com', NULL, 'TH', 'asia', 'en', 'html', 70),
('The Australian', 'theaustralian.com.au', NULL, 'AU', 'asia', 'en', 'html', 80),
('Sydney Morning Herald', 'smh.com.au', 'https://www.smh.com.au/rss/feed.xml', 'AU', 'asia', 'en', 'rss', 80),
('ABC News AU', 'abc.net.au', 'https://www.abc.net.au/news/feed/51120/rss.xml', 'AU', 'asia', 'en', 'rss', 80),
('New Zealand Herald', 'nzherald.co.nz', NULL, 'NZ', 'asia', 'en', 'html', 70),

-- MIDDLE EAST
('The National', 'thenationalnews.com', NULL, 'AE', 'middle_east', 'en', 'html', 75),
('Arab News', 'arabnews.com', NULL, 'SA', 'middle_east', 'en', 'html', 75),
('Haaretz', 'haaretz.com', NULL, 'IL', 'middle_east', 'en', 'html', 80),
('Jerusalem Post', 'jpost.com', 'https://www.jpost.com/rss/rssfeedsfrontpage.aspx', 'IL', 'middle_east', 'en', 'rss', 75),
('Times of Israel', 'timesofisrael.com', 'https://www.timesofisrael.com/feed/', 'IL', 'middle_east', 'en', 'rss', 75),
('Daily Sabah', 'dailysabah.com', 'https://www.dailysabah.com/rssFeed/home', 'TR', 'middle_east', 'en', 'rss', 70),
('Tehran Times', 'tehrantimes.com', NULL, 'IR', 'middle_east', 'en', 'html', 60),
('Gulf News', 'gulfnews.com', NULL, 'AE', 'middle_east', 'en', 'html', 70),
('Dawn', 'dawn.com', 'https://www.dawn.com/feeds/home', 'PK', 'middle_east', 'en', 'rss', 70),

-- AFRICA
('Mail & Guardian', 'mg.co.za', NULL, 'ZA', 'africa', 'en', 'html', 70),
('Daily Maverick', 'dailymaverick.co.za', NULL, 'ZA', 'africa', 'en', 'html', 70),
('The East African', 'theeastafrican.co.ke', NULL, 'KE', 'africa', 'en', 'html', 65),
('The Nation (KE)', 'nation.africa', NULL, 'KE', 'africa', 'en', 'html', 65),
('Punch NG', 'punchng.com', NULL, 'NG', 'africa', 'en', 'html', 65),
('Premium Times', 'premiumtimesng.com', NULL, 'NG', 'africa', 'en', 'html', 65),
('Egypt Independent', 'egyptindependent.com', NULL, 'EG', 'africa', 'en', 'html', 60),
('The Africa Report', 'theafricareport.com', NULL, 'FR', 'africa', 'en', 'html', 70),

-- AMERICAS (NON-US)
('Globe and Mail', 'theglobeandmail.com', NULL, 'CA', 'americas', 'en', 'html', 80),
('CBC News', 'cbc.ca', 'https://www.cbc.ca/cmlink/rss-topstories', 'CA', 'americas', 'en', 'rss', 85),
('Toronto Star', 'thestar.com', NULL, 'CA', 'americas', 'en', 'html', 75),
('Folha de S.Paulo', 'folha.uol.com.br', NULL, 'BR', 'americas', 'pt', 'html', 80),
('O Globo', 'oglobo.globo.com', NULL, 'BR', 'americas', 'pt', 'html', 75),
('La Nación', 'lanacion.com.ar', NULL, 'AR', 'americas', 'es', 'html', 75),
('Clarín', 'clarin.com', NULL, 'AR', 'americas', 'es', 'html', 75),
('El Universal', 'eluniversal.com.mx', NULL, 'MX', 'americas', 'es', 'html', 75),
('Reforma', 'reforma.com', NULL, 'MX', 'americas', 'es', 'html', 70),
('El Mercurio', 'emol.com', NULL, 'CL', 'americas', 'es', 'html', 70),
('El Tiempo', 'eltiempo.com', NULL, 'CO', 'americas', 'es', 'html', 70),

-- ENERGY & INDUSTRY
('Energy Voice', 'energyvoice.com', 'https://www.energyvoice.com/feed/', 'GB', 'energy', 'en', 'rss', 85),
('Offshore Engineer', 'oedigital.com', NULL, 'US', 'energy', 'en', 'html', 75),
('Recharge News', 'rechargenews.com', NULL, 'NO', 'energy', 'en', 'html', 85),
('Windpower Monthly', 'windpowermonthly.com', NULL, 'GB', 'energy', 'en', 'html', 80),
('PV Magazine', 'pv-magazine.com', 'https://www.pv-magazine.com/feed/', 'DE', 'energy', 'en', 'rss', 80),
('Upstream Online', 'upstreamonline.com', NULL, 'NO', 'energy', 'en', 'html', 80),
('Rigzone', 'rigzone.com', 'https://www.rigzone.com/news/rss/rigzone_latest.aspx', 'US', 'energy', 'en', 'rss', 75),
('Greentech Media', 'greentechmedia.com', NULL, 'US', 'energy', 'en', 'html', 75),
('Carbon Brief', 'carbonbrief.org', 'https://www.carbonbrief.org/feed/', 'GB', 'energy', 'en', 'rss', 80),
('CleanTechnica', 'cleantechnica.com', 'https://cleantechnica.com/feed/', 'US', 'energy', 'en', 'rss', 75),
('Renew Economy', 'reneweconomy.com.au', 'https://reneweconomy.com.au/feed/', 'AU', 'energy', 'en', 'rss', 70),
('Utility Dive', 'utilitydive.com', NULL, 'US', 'energy', 'en', 'html', 75),
('S&P Global Energy', 'spglobal.com', NULL, 'US', 'energy', 'en', 'html', 85),
('World Oil', 'worldoil.com', NULL, 'US', 'energy', 'en', 'html', 70),
('Offshore Technology', 'offshore-technology.com', 'https://www.offshore-technology.com/feed/', 'GB', 'energy', 'en', 'rss', 80),
('Ocean Energy Europe', 'oceanenergy-europe.eu', NULL, 'BE', 'energy', 'en', 'html', 75),

-- TECH
('TechCrunch', 'techcrunch.com', 'https://techcrunch.com/feed/', 'US', 'tech', 'en', 'rss', 85),
('The Verge', 'theverge.com', 'https://www.theverge.com/rss/index.xml', 'US', 'tech', 'en', 'rss', 80),
('Ars Technica', 'arstechnica.com', 'https://feeds.arstechnica.com/arstechnica/index', 'US', 'tech', 'en', 'rss', 80),
('Wired', 'wired.com', 'https://www.wired.com/feed/rss', 'US', 'tech', 'en', 'rss', 80),
('MIT Technology Review', 'technologyreview.com', 'https://www.technologyreview.com/feed/', 'US', 'tech', 'en', 'rss', 80),
('ZDNet', 'zdnet.com', NULL, 'US', 'tech', 'en', 'html', 70),
('The Register', 'theregister.com', 'https://www.theregister.com/headlines.atom', 'GB', 'tech', 'en', 'atom', 70),
('Hacker News', 'news.ycombinator.com', 'https://news.ycombinator.com/rss', 'US', 'tech', 'en', 'rss', 75)

ON CONFLICT (domain) DO NOTHING;
